# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: gh-pages-build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install MdBook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.28/mdbook-v0.4.28-x86_64-unknown-linux-musl.tar.gz -o mdbook.tar.gz \
          && tar -xf ./mdbook.tar.gz \
          && rm ./mdbook.tar.gz
      - name: install preprocessor
        run: |
          curl -L https://github.com/FreeMasen/mdbook-presentation-preprocessor/releases/download/v0.3.1/mdbook-presentation-preprocessor-v0.3.1-x86_64-unknown-linux-gnu.tar.xz -o ./mpp.tar.xz \
          && tar -xf ./mpp.tar.xz \
          && rm ./mpp.tar.xz \
          && mv ./mdbook-presentation-preprocessor-v0.3.1-x86_64-unknown-linux-gnu/mdbook-presentation-preprocessor . \
          && rm -r ./mdbook-presentation-preprocessor-v0.3.1-x86_64-unknown-linux-gnu
      # Runs a set of commands using the runners shell
      - name: run mdbook build
        run: ./mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
